config/routes.rb
Rails.application.routes.draw do
 
  resources :projects
  get 'dislikes/index'

  get 'dislikes/destroy'

  get 'likes/index'

  get 'likes/destroy'

  get 'likes/destroy', to: "likes#destroy"

  get 'myquestions/index'

  get 'questions/answeredque'  

  get 'questions/myquestionsindex'
  
  get 'questions/interestwisequestions'

  get 'questions/changetext'

  get 'questions/searchtext'


  get 'home/aboutus'

root  "home#index"
 




  resources :questions do
  		resources :answers
  	end
  	
  resources :userdetails
  devise_for :users, controllers: { registrations: "registrations" }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord

	belongs_to :user
	has_many :answers, dependent: :destroy
	belongs_to :subject
	validates :userquestion, :presence => true
	validates :userquestion, :length => {:minimum => 9}
	validates :userquestion, :uniqueness =>true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
 before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  # GET /questions
  # GET /questions.json
  def index

    @questions =Question.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    @userdtl = Userdetail.all
    @subjects = Subject.all
     if !Userdetail.exists?(user_id: current_user.id) 
        redirect_to new_userdetail_path 
      end
    @newquestions =Question.last(5).reverse

    @cnt=Answer.where(:user_id =>current_user.id).count
    @unanswered=Question.all.count-@cnt

  end



 def myquestionsindex
    @questions = Question.all
    @userdtl = Userdetail.all
    @subjects = Subject.all
    if !Userdetail.exists?(user_id: current_user.id) 
        redirect_to new_userdetail_path 
    end

    @newquestions =Question.last(5).reverse
    @cnt=Answer.where(:user_id =>current_user.id).count
  end


 def interestwisequestions
    @questions = Question.paginate(:page => params[:page], :per_page => 10)
       @userdtl = Userdetail.all
       @subjects = Subject.all
       @sub = params[:subjectname]
     if !Userdetail.exists?(user_id: current_user.id) 
        redirect_to new_userdetail_path 
      end

    @newquestions =Question.last(5).reverse
    @cnt=Answer.where(:user_id =>current_user.id).count
  end



  def changetext
    @questions =Question.all
    @answers = Answer.all
    @userdtl = Userdetail.all
    @subjects = Subject.all
    @userq = params[:userquestion]
    @result = ""
    require 'open3'
    @questions.each do | que |
        cmd = 'echo "'+que.userquestion+'" | grep -i "'+@userq+'"' 
        stdin, @stdout, stderr, wait_thr = Open3.popen3(cmd)
        @result = @result + @stdout.read 
        end
  
      
    respond_to do | format |
        format.js
      end
  end


def searchtext
    @questions =Question.all
    @answers = Answer.all
    @userdtl = Userdetail.all
    @subjects = Subject.all
    @userq = params[:q]
    @result = ""
    require 'open3'
    @questions.each do | que |
        cmd = 'echo "'+que.userquestion+'" | grep -i "'+@userq+'"' 
        stdin, @stdout, stderr, wait_thr = Open3.popen3(cmd)
        @result = @result + @stdout.read 
    end
  
  @userdtl.each do | dtl |
        cmd = 'echo "'+dtl.firstname+' '+dtl.lastname+'" | grep -i "'+@userq+'"' 
        stdin, @stdout, stderr, wait_thr = Open3.popen3(cmd)
        @result = @result +  @stdout.read 
    end
  

    respond_to do | format |
        format.js
      end
  end





  
  def answeredque
     @questions = Question.paginate(:page => params[:page], :per_page => 10)
    @answers = Answer.all
       @userdtl = Userdetail.all
       @subjects = Subject.all
       @likes=Like.all
       @dislikes = Dislike.all
     if !Userdetail.exists?(user_id: current_user.id) 
        redirect_to new_userdetail_path 
      end

    @newquestions =Question.last(5).reverse
    @cnt=Answer.where(:user_id =>current_user.id).count
   @answerd_questions=Answer.where(:user_id=>current_user.id)
    

  end



  # GET /questions/1
  # GET /questions/1.json
  def show
    @questions= Question.all
    @question= Question.find(params[:id])
    @subjects = Subject.all
    @answers = @question.answers.paginate(:page => params[:page], :per_page =>10)
    @userdtl = Userdetail.all
    @likes = Like.all
    @dislikes = Dislike.all
    @newquestions =Question.last(5).reverse

    @cnt=Answer.where(:user_id =>current_user.id).count
    @unanswered=Question.all.count-@cnt
    
  end

  # GET /questions/new
  def new
    @userdtl = Userdetail.all
    @question = Question.new

    #@answer = Answer.new(question_id: params[:question_id])
  end

  # GET /questions/1/edit
  def edit
  end


  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id=current_user.id
    @userdtl = Userdetail.all


    require 'open3'
    cmd = 'gingerice "'+question_params[:userquestion]+'?"'
    stdin, @stdout, stderr, wait_thr = Open3.popen3(cmd) 
    @question.userquestion = @stdout.read



    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path, notice: @stdout.read }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:userquestion,:question_id, :user_id, :subject_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_suggs.html.erb
<%= que.answers.count %>

app/views/questions/answeredque.html.erb
<html>
<style>
.forum-thread-card {
    display: block;
    border-radius: 5px;
    margin-left: 12px;
    padding: 0px 10px 0px 60px;
    position: relative;
}
.panel {
    margin-bottom: 24px;
    background-color: #fff;
    border: 2px solid transparent;
    border-radius: 4px;
    -webkit-box-shadow: 0 1px 1px rgba(0,0,0,0.05);
    box-shadow: 0 1px 1px rgba(0,0,0,0.05);
}
hr {
    margin-top: 24px;
    margin-bottom: 24px;
    border: 0;
    width:100%;
    border-top: 1px solid #eeeeee;

}
.h-divider{
 margin-top:15px;
 margin-bottom:24px;
 height:1px;
 width:100%;
 border-top:1px solid #bdbdbd;
}
.body{
  font-size: 25px;
line-height: 1.5;
color: #555555;
-webkit-text-size-adjust: 100%;
box-sizing: border-box;
}

.forum_post {
    position: relative;
    border-radius: 5px;
}
.forum_post.original-poster {
    background-color: #f7f7fa;
    margin: -15px;
    padding: 15px;
}
.forum_post .forum-post-header {
    margin-left: 65px;
}
.forum_post .forum-post-body {
    margin-left: 65px;
}
.forum_post .forum-post-actions {
    border-top: 1px solid #efefef;
    overflow: hidden;
    padding: 10px 0px;
}
</style>



<body>
<%= render 'layouts/header.html' %>
<p id="notice"><%= notice %></p>
  <!-- container fuild strat-->
  <div class="container-fluid">
      <!--Side bar -->
      <%= render "layouts/leftstack" %>
      <!--side bar end-->
      
      <!-- col starts -->
        <div class="col-sm-9">

                <div class="alert alert-info">
                  <p><strong><a href="/pricing">IOB</a></strong> to join the conversation. Ask questions about your code, get help adding a new feature, and discuss implementation details with other members.</p>
                </div>
<% @answerd_questions.each do |answer| %>
                  <!-- panel default start -->
                  <div class="panel panel-default">
                    <div class="panel-body">
                      <!-- Question-->
                      <h1><i class="fa fa-thumb-tack text-muted"></i> <%= @questions.find( answer.question_id).userquestion %></h1>
                        <p class="thread-details">
                          <strong style="color: #4ea1d3"><%= @questions.find(answer.question_id).subject.subjectname %></strong>
                          • Asked <time datetime="2016-10-26T16:35:23Z" data-local="time-ago"><%=time_ago_in_words(@questions.find(answer.question_id).created_at)%></time> ago by <%= link_to @userdtl.find(@questions.find(answer.question_id).user_id).firstname.upcase, userdetail_path(answer.user_id) ,:style=>" color: #4ea1d3"%>
                        </p>

                      <br>
                <!-- end question --> 
            <!-- answers start -->
              <div class="forum_post original-poster" id="forum_post_2566">
                <div class="forum-post-header">
                    <%= image_tag @userdtl.find(answer.user_id).image, class: 'img-rounded avatar pull-left', style: 'height:40px;width:40px; margin-right:20px' %>


                      <p>
                      <strong class="forum-post-user" style="color: #4ea1d3"><%= link_to 'You', userdetail_path(answer.user_id) %></strong>
                      <small><span class="label label-default" data-toggle="tooltip" title="" data-original-title="1-Month Subscriber"><i class="fa fa-diamond"></i></span> <span class="label label-primary"><%= link_to @userdtl.find(answer.user_id).usertype, userdetail_path(answer.user_id) %></span> answered <time datetime="2016-10-26T16:35:23Z" data-local="time" data-format="%b %d, %Y" data-localized="true"><%= time_ago_in_words(answer.created_at)%></time> ago </small>
                      </p>
                </div>

                <div class="forum-post-body">
                    <p><%= answer.useranswer.html_safe %></p>

                    <div class="forum-post-actions">

                          <div data-behavior="reactions" data-id="2566">
                              <!---Likes -->
                              <i class="fa fa-smile-o"></i>
                              <% if !@likes.exists?(user_id: current_user.id, answer_id: answer.id) %>
                                 <%= %>

                                  <%= link_to ("<button class='btn'><i class='fa fa-thumbs-up icon'></i></button>").html_safe,  likes_index_path(:question_id => @questions.find( answer.question_id),:answer_id => answer.id,:frompage => 'answeredquestions') %>
                                  <%= @likes.where(:answer_id => answer.id).count %>
                              <% else %>
                                  <%= link_to ("<button class='btn'><i class='fa fa-thumbs-up text-primary icon'></i></button>").html_safe,  likes_destroy_path(:question_id => @questions.find( answer.question_id),:answer_id => answer.id, :frompage => 'answeredquestions') %>
                                  <%= @likes.where(:answer_id => answer.id).count  %>
                               <% end %>
                                <!---Dislikes -->
                                <% if !@dislikes.exists?(user_id: current_user.id, answer_id: answer.id) %>
                                    <%= link_to ("<button class='btn'><i class='fa fa-thumbs-down icon'></i></button>").html_safe, dislikes_index_path(:question_id => @questions.find( answer.question_id),:answer_id => answer.id, :frompage => 'answeredquestions')%>
                                    <%= @dislikes.where(:answer_id => answer.id).count %>
                                <% else %>
                                    <%= link_to ("<button class='btn'><i class='fa fa-thumbs-down text-primary icon'></i></button>").html_safe, dislikes_destroy_path(:question_id => @questions.find( answer.question_id),:answer_id => answer.id, :frompage => 'answeredquestions') %>
                                    <%= @dislikes.where(:answer_id => answer.id).count %>
                                 <% end %>
                          
                          </div>

                      </div>

                  </div>
                  <!-- forum post body end -->
                </div>
                <hr>
              
              
    </div>
    </div>
    <%end%>
   <!-- panel default ends -->

      </div>

      <!-- col ends -->

  </div>
  <!-- container fluid end -->
  <%= render "layouts/footer" %>
</body>
</html>

app/views/questions/changetext.js.erb
$("#suggestions").text('')

var cnt = 0


<% @questions.each do |question| %>
        <% if @result.include? question.userquestion %>
    
if(cnt <=2)
{
  $("#suggestions").append('<%= j link_to question.userquestion, question_path(question.id) %><br>')
  $("#suggestions").append('<%= j @subjects.find(question.subject_id).subjectname %> ') 
  $("#suggestions").append(' • <%= j render "suggs", que: question %> Answers • Asked by ')
  $("#suggestions").append('<%= j link_to @userdtl.find(question.user_id).firstname, userdetail_path(question.user_id) %>') 
  $("#suggestions").append('<hr style="border-top: 1px dotted #8c8b8b; width:100%">')
}
else
{
  }
cnt++;
<% end %>
  
<% end %>


var x = '<%= @userq %>'
   if(x=="")
   {
   	$("#suggestions").text('')
   }



    
    	
   

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<html>
<body>
<%= render "layouts/header" %>
<div class="container-fluid">

<style>
.forum-thread-card {
    display: block;
    border-radius: 5px;
    margin-left: 12px;
    padding: 0px 10px 0px 60px;
    position: relative;
}
.panel {
    margin-bottom: 24px;
    background-color: #fff;
    border: 2px solid transparent;
    border-radius: 4px;
    -webkit-box-shadow: 0 1px 1px rgba(0,0,0,0.05);
    box-shadow: 0 1px 1px rgba(0,0,0,0.05);
}
hr {
    margin-top: 24px;
    margin-bottom: 24px;
    border: 0;
    width:100%;
    border-top: 1px solid #eeeeee;

}
.h-divider{
 margin-top:15px;
 margin-bottom:24px;
 height:1px;
 width:100%;
 border-top:1px solid #bdbdbd;
}
.body{
  font-size: 25px;
line-height: 1.5;
color: #555555;
-webkit-text-size-adjust: 100%;
box-sizing: border-box;
}
</style>



<div class="modal" id="loginModal">
    <div class="modal-dialog" style="height: 50px; padding-top:10%;">
    <!-- Modal content-->
    <div class="modal-content" style="height: 50px;width: 800px; text-align: 20px;overflow:visible;">
         
      
      <div class="modal-body" style=" height: 50px; overflow: auto;">
      
      </div>


    </div>
  </div>
</div>

  <div class="container-fluid ">
    
      <!--Side bar -->
      <%= render "layouts/leftstack" %>
    <!--side bar end-->
    
    <!-- end of col md 3 -->
    <!-- forum question start -->
      <div class="col-sm-9">
          <div class="alert alert-info">
            <p><strong>IOB</strong> to join the conversation. Ask questions about your code, get help adding a new feature, and discuss implementation details with other members.</p>
          </div>


          <div class="panel panel-default">
            <div class="panel-body">
               <% @questions.each do |question| %>
                  <% if question.user_id != current_user.id %>
                      <!-- single question -->
                      <div class="forum-thread-card" style= "border-bottom: 1px #bdbdbd;" >
                          <div class="row">
                          <a class="thread-posts-count pull-right" href="#">
                            <span class="badge badge-theme" style="background-color:#158CBA;"><%= question.answers.count%>
                                <small>answers</small>
                            </span>
                          </a>

                                <h4>
                                <%= image_tag @userdtl.find(question.user_id).image, class: 'img-rounded avatar pull-left', style: 'height:40px;width:40px; margin-right:20px' %>

                                    <i class="fa fa-thumb-tack fa-text-muted text-muted"></i> 
                                    <%= link_to question.userquestion, question %>
                                  
                                </h4>

                                <div class="thread-details">
                                  <strong><a style="color: #4ea1d3" href="#"><%= question.subject.subjectname.upcase %></a></strong>
                                  • Asked <time datetime="2016-10-26T16:35:23Z" data-local="time-ago"><%= time_ago_in_words(question.created_at)%> ago </time> by <%= link_to @userdtl.find(question.user_id).firstname.upcase, userdetail_path(question.user_id) ,:style=>"color:#158CBA"%> 
                                </div>
                          </div>  
                          <br>
                    </div>

                    <div class="h-divider">
                  </div>
                  <% end %>
              
               <% end %>
              <!-- single question end -->

              <div class="text-center"><%= will_paginate @questions , :renderer => BootstrapPagination::Rails %>
              </div>
              

            </div> <!-- panel body -->
          </div> <!-- panel default -->

      </div>
     
     

    <!-- forum questions end -->
    <!-- question list end -->
   
           

        </div>



<br>


</div>
    
<%= render "layouts/footer" %>

</body>
</html>

app/views/questions/interestwisequestions.html.erb
<html>
<body>
<%= render "layouts/header" %>
<div class="container-fluid">

<style>
.forum-thread-card {
    display: block;
    border-radius: 5px;
    margin-left: 12px;
    padding: 0px 10px 0px 60px;
    position: relative;
}
.panel {
    margin-bottom: 24px;
    background-color: #fff;
    border: 2px solid transparent;
    border-radius: 4px;
    -webkit-box-shadow: 0 1px 1px rgba(0,0,0,0.05);
    box-shadow: 0 1px 1px rgba(0,0,0,0.05);
}
hr {
    margin-top: 24px;
    margin-bottom: 24px;
    border: 0;
    width:100%;
    border-top: 1px solid #eeeeee;

}
.h-divider{
 margin-top:15px;
 margin-bottom:24px;
 height:1px;
 width:100%;
 border-top:1px solid #bdbdbd;
}
</style>



<div class="modal" id="loginModal">
    <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

  <div class="container-fluid ">
    
      <!--Side bar -->
      <%= render "layouts/leftstack" %>
    <!--side bar end-->
    
    <!-- forum question start -->
      <div class="col-sm-9">
          <div class="alert alert-info">
            <p><strong><a href="#">IOB</a></strong> to join the conversation. Ask questions about your code, get help adding a new feature, and discuss implementation details with other members.</p>
          </div>


          <div class="panel panel-default">
            <div class="panel-body">
               <% @questions.each do |question| %>
               <% if @subjects.find(question.subject_id).subjectname == @sub %>
                      <!-- single question -->
                      <div class="forum-thread-card" style= "border-bottom: 1px #bdbdbd;" >
                          <div class="row">
                          <a class="thread-posts-count pull-right" href="#">
                            <span class="badge badge-theme" style="background-color:#158CBA;"><%= question.answers.count%>
                                <small>answers</small>
                            </span>
                          </a>

                                <h4>
                                <%= image_tag @userdtl.find(question.user_id).image, class: 'img-rounded avatar pull-left', style: 'height:40px;width:40px; margin-right:20px' %>

                                    <i class="fa fa-thumb-tack fa-text-muted text-muted"></i> 
                                    <%= link_to question.userquestion, question %>
                                  
                                </h4>

                                <div class="thread-details">
                                  <strong><a style="color: #4ea1d3" href="#"><%= question.subject.subjectname %></a></strong>
                                  • Asked <time datetime="2016-10-26T16:35:23Z" data-local="time-ago"><%= time_ago_in_words(question.created_at)%> </time> by <%= link_to @userdtl.find(question.user_id).firstname, userdetail_path(question.user_id) %> 
                                </div>
                          </div>  
                          <br>
                    </div>

                    <div class="h-divider">
                  </div>
              
              <% end %>
               <% end %>
              <!-- single question end -->


              <div class="text-center"><%= will_paginate @questions , :renderer => BootstrapPagination::Rails %>
              </div>
              

              </div>
              

            </div> <!-- panel body -->
          </div> <!-- panel default -->

      </div>
     
     

    <!-- forum questions end -->
    <!-- question list end -->
   
           

        </div>



<br>


</div>
    
<%= render "layouts/footer" %>

</body>
</html>

app/views/questions/new.html.erb
<%= render 'form', question: @question %>

app/views/questions/searchtext.js.erb
$("#box1").text('')
$('#myModal').modal({
        show: 'true'
    });
var cnt = 0
<% @userdtl.each do |user| %>
        <% if @result.include? user.firstname %>
    
if(cnt <=2)
{
  $("#box1").append('Profile: <%= j link_to user.firstname+" "+user.lastname, userdetail_path(user.id) %>')
  $("#box1").append('<hr style="border-top: 1px dotted #8c8b8b; width:100%">')
}
else
{
  }
cnt++;
<% end %>
  
<% end %>

var cnt=0

<% @questions.each do |question| %>
        <% if @result.include? question.userquestion %>
    
if(cnt <=2)
{
  $("#box1").append('Topic: <%= j @subjects.find(question.subject_id).subjectname %><br>') 
  $("#box1").append('Question: <%= j link_to question.userquestion, question_path(question.id) %>')
  $("#box1").append('<hr style="border-top: 1px dotted #8c8b8b; width:100%">')
}
else
{
  }
cnt++;
<% end %>
  
<% end %>

var x = '<%= @userq %>'
   if(x=="")
   {
   	$("#box1").text('')
   }



    
    	
   

app/views/questions/show.html.erb
<html>
<style>

.forum-thread-card {
    display: block;
    border-radius: 5px;
    margin-left: 12px;
    padding: 0px 10px 0px 60px;
    position: relative;
}
.panel {
    margin-bottom: 24px;
    background-color: #fff;
    border: 2px solid transparent;
    border-radius: 4px;
    -webkit-box-shadow: 0 1px 1px rgba(0,0,0,0.05);
    box-shadow: 0 1px 1px rgba(0,0,0,0.05);
}
hr {
    margin-top: 24px;
    margin-bottom: 24px;
    border: 0;
    width:100%;
    border-top: 1px solid #eeeeee;

}
.h-divider{
 margin-top:15px;
 margin-bottom:24px;
 height:1px;
 width:100%;
 border-top:1px solid #bdbdbd;
}
.body{
  font-size: 25px;
line-height: 1.5;
color: #555555;
-webkit-text-size-adjust: 100%;
box-sizing: border-box;
}

.forum_post {
    position: relative;
    border-radius: 5px;
}
.forum_post.original-poster {
    background-color: #f7f7fa;
    margin: -15px;
    padding: 15px;
}
.forum_post .forum-post-header {
    margin-left: 65px;
}
.forum_post .forum-post-body {
    margin-left: 65px;
}
.forum_post .forum-post-actions {
    border-top: 1px solid #efefef;
    overflow: hidden;
    padding: 10px 0px;
}
</style>

 

<body>


<div class="modal" id="loginModal">
    <div class="modal-dialog" style="height: 50px; padding-top:10%;">
    <!-- Modal content-->
    <div class="modal-content" style="height: 50px;width: 800px; text-align: 20px;overflow:visible;">
      
      <div class="modal-body" style=" height: 50px; overflow: auto;">
      </div>
    </div>
  </div>
</div>

<%= render 'layouts/header.html' %>
<p id="notice"><%= notice %></p>
  <!-- container fuild strat-->
  <div class="container-fluid">
      <!--Side bar -->
      <%= render "layouts/leftstack" %>
      <!--side bar end-->
      
      <!-- col starts -->
        <div class="col-sm-9">

                <div class="alert alert-info">
                  <p><strong>IOB</strong> to join the conversation. Ask questions about your code, get help adding a new feature, and discuss implementation details with other members.</p>
                </div>

                  <!-- panel default start -->
                  <div class="panel panel-default">
                    <div class="panel-body">
                      <!-- Question-->
                      <h1><i class="fa fa-thumb-tack text-muted"></i> <%= @question.userquestion %></h1>
                        <p class="thread-details">
                          <strong style="color: #4ea1d3"><%= @question.subject.subjectname %></strong>
                          • Asked <time datetime="2016-10-26T16:35:23Z" data-local="time-ago"><%=time_ago_in_words(@question.created_at)%></time> ago by <%= link_to @userdtl.find(@question.user_id).firstname.upcase, userdetail_path(@question.user_id) ,:style=>" color: #4ea1d3"%>
                        </p>

                      <br>
                <!-- end question --> 
            <!-- answers start -->
            <% @answers.each do |ans| %>  
              <div class="forum_post original-poster" id="forum_post_2566">
                <div class="forum-post-header">
                    <%= image_tag @userdtl.find(ans.user_id).image, class: 'img-rounded avatar pull-left', style: 'height:40px;width:40px; margin-right:20px' %>


                      <p>
                      <strong class="forum-post-user" style="color: #4ea1d3"><%= link_to @userdtl.find(ans.user_id).firstname.upcase, userdetail_path(ans.user_id) %></strong>
                      <small><span class="label label-default" data-toggle="tooltip" title="" data-original-title="1-Month Subscriber"><i class="fa fa-diamond"></i></span> <span class="label label-primary"><%=  @userdtl.find(ans.user_id).usertype %></span> answered <time datetime="2016-10-26T16:35:23Z" data-local="time" data-format="%b %d, %Y" data-localized="true"><%= time_ago_in_words(ans.created_at)%></time> ago :</small>
                      </p>
                </div>

                <div class="forum-post-body">
                    <p><%= ans.useranswer.html_safe %></p>

                    <div class="forum-post-actions">

                          <div data-behavior="reactions" data-id="2566">
                              <!---Likes -->
                              <i class="fa fa-smile-o"></i>
                              <% if !@likes.exists?(user_id: current_user.id, answer_id: ans.id) %>
                                 <%= %>

                                  <%= link_to ("<button class='btn'><i class='fa fa-thumbs-up icon'></i></button>").html_safe,  likes_index_path(:question_id => @question.id,:answer_id => ans.id, :frompage => 'questions') %>
                                  <%= @likes.where(:answer_id => ans.id).count %>
                              <% else %>
                                  <%= link_to ("<button class='btn'><i class='fa fa-thumbs-up text-primary icon'></i></button>").html_safe,  likes_destroy_path(:question_id => @question.id,:answer_id => ans.id, :frompage => 'questions') %>
                                  <%= @likes.where(:answer_id => ans.id).count  %>
                               <% end %>
                                <!---Dislikes -->
                                <% if !@dislikes.exists?(user_id: current_user.id, answer_id: ans.id) %>
                                    <%= link_to ("<button class='btn'><i class='fa fa-thumbs-down icon'></i></button>").html_safe, dislikes_index_path(:question_id => @question.id,:answer_id => ans.id, :frompage => 'questions')%>
                                    <%= @dislikes.where(:answer_id => ans.id).count %>
                                <% else %>
                                    <%= link_to ("<button class='btn'><i class='fa fa-thumbs-down text-primary icon'></i></button>").html_safe, dislikes_destroy_path(:question_id => @question.id,:answer_id => ans.id, :frompage => 'questions') %>
                                    <%= @dislikes.where(:answer_id => ans.id).count %>
                                 <% end %>
                          
                               
                          </div>

                      </div>

                  </div>
                  <!-- forum post body end -->
                </div>
                <hr>
              <%end%>

                <%= render "answers/form"%>
              <div class="text-center"><%= will_paginate @answers  , :renderer => BootstrapPagination::Rails %>
              </div>
              
    </div>
    </div>
   <!-- panel default ends -->

      </div>

      <!-- col ends -->

  </div>
  <!-- container fluid end -->
  <%= render "layouts/footer" %>
</body>
</html>