config/routes.rb
Rails.application.routes.draw do
 
  resources :projects
  get 'dislikes/index'

  get 'dislikes/destroy'

  get 'likes/index'

  get 'likes/destroy'

  get 'likes/destroy', to: "likes#destroy"

  get 'myquestions/index'

  get 'questions/answeredque'  

  get 'questions/myquestionsindex'
  
  get 'questions/interestwisequestions'

  get 'questions/changetext'

  get 'questions/searchtext'


  get 'home/aboutus'

root  "home#index"
 




  resources :questions do
  		resources :answers
  	end
  	
  resources :userdetails
  devise_for :users, controllers: { registrations: "registrations" }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :user 
	belongs_to :question 
	has_many :likes, dependent: :destroy
	has_many :dislikes, dependent: :destroy

	validates :useranswer, :presence => true
	validates :useranswer, :length => {:minimum => 10}
	validates :useranswer, :uniqueness =>true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dislike.rb
class Dislike < ApplicationRecord
	belongs_to :user
	belongs_to :answer  
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :answer  
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	validates :title,:technology, :presence => true
	validates :title,:technology, :length => {:minimum => 4}
end

app/models/question.rb
class Question < ApplicationRecord

	belongs_to :user
	has_many :answers, dependent: :destroy
	belongs_to :subject
	validates :userquestion, :presence => true
	validates :userquestion, :length => {:minimum => 9}
	validates :userquestion, :uniqueness =>true
end

app/models/subject.rb
class Subject < ApplicationRecord

	#belongs_to :user
	has_many :questions, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

	 has_many :subjects, dependent: :destroy
	 has_many :questions, dependent: :destroy
	 has_many :answers, dependent: :destroy
   has_many :projects, dependent: :destroy
   has_one :userdetail, dependent: :destroy
   has_one :like, dependent: :destroy
   has_one :dislike, dependent: :destroy
end

app/models/userdetail.rb
class Userdetail < ApplicationRecord
	
	has_attached_file :image, styles: { medium: "50x50#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	belongs_to :user

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

     if user_signed_in?
  	 	if Userdetail.exists?(user_id: current_user.id)
           
      			redirect_to  questions_path
      	else
      			redirect_to new_userdetail_path 
      	end

    else
      redirect_to new_user_session_path
    end

  end

  def aboutus 
      @userdtl=Userdetail.all
     
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  		@newlike = Like.new()
  		@newlike.user_id = current_user.id
  		@newlike.answer_id = params[:answer_id]
      @dislike = Dislike.where(:user_id => current_user.id, :answer_id => params[:answer_id])



      if @dislike.count != 0
        Dislike.destroy(@dislike)
      end
  		if @newlike.save
        if params[:frompage] == 'answeredquestions'
          redirect_to questions_answeredque_path
        else
  			redirect_to question_path(params[:question_id])
        end
  		end 
  	end


  def destroy
  	@newlike = Like.where(:user_id => current_user.id, :answer_id => params[:answer_id])
  	Like.destroy(@newlike)
  	redirect_to question_path(params[:question_id])

  end
end

app/controllers/userdetails_controller.rb
class UserdetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_userdetail, only: [:show, :edit, :update, :destroy]

  # GET /userdetails
  # GET /userdetails.json
  def index


    @userdetails = Userdetail.all
    
    redirect_to questions_path
  end

  # GET /userdetails/1
  # GET /userdetails/1.json
  def show
    @userdtl = Userdetail.all
    @userid=params[:user_id]
    @projects = Project.where(:user_id=>@userdetail.user_id)
    @project = Project.new
    @questions=Answer.all
    #@array=@userdetails.interests.split("")

  end

  # GET /userdetails/new
  def new
    @userdetail = Userdetail.new
    @subjects= Subject.all
  end

  # GET /userdetails/1/edit
  def edit
    @subjects= Subject.all
    @userdtl = Userdetail.all
    
  end

  # POST /userdetails
  # POST /userdetails.json
  def create
    @userdetail = Userdetail.new(userdetail_params)
    @userdetail.user_id=current_user.id
    respond_to do |format|
      if @userdetail.save
        format.html { redirect_to @userdetail, notice: 'Userdetail was successfully created.' }
        format.json { render :show, status: :created, location: @userdetail }
      else
        format.html { render :new }
        format.json { render json: @userdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userdetails/1
  # PATCH/PUT /userdetails/1.json
  def update
    respond_to do |format|
      if @userdetail.update(userdetail_params)
        format.html { redirect_to @userdetail, notice: 'Userdetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @userdetail }
      else
        format.html { render :edit }
        format.json { render json: @userdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userdetails/1
  # DELETE /userdetails/1.json
  def destroy
    @userdetail.destroy
    respond_to do |format|
      format.html { redirect_to userdetails_url, notice: 'Userdetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userdetail
      @userdetail = Userdetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userdetail_params
      params.require(:userdetail).permit(:image,:firstname, :lastname, :dateofbirth, :usertype,:qualification,:gender, :country, interests:[])
    end
end

app/helpers/answeredque_helper.rb
module AnsweredqueHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/myquestions_helper.rb
module MyquestionsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/userdetails_helper.rb
module UserdetailsHelper

	def checked(area)
		@userdetail.interests.nil? ? false : @userdetail.interests.match(area)
	end
end

app/views/userdetails/_form.html.erb
<body>
<%= form_for(userdetail) do |f| %>
  <% if userdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userdetail.errors.count, "error") %> prohibited this userdetail from being saved:</h2>

      <ul>
      <% userdetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
    <h1>Edit Profile</h1>
    <hr>
  <div class="row">
      <!-- left column -->
      <div class="col-md-3">
        <div class="text-center">
          <img id="img_prev" src="#" class="avatar img-circle"  alt="Avatar">
              <h6>Upload a different photo...</h6>
              <%= f.file_field :image,{:onchange=>"readURL(this)"} %>
        </div>
      </div>
      
      <!-- edit form column -->
      <div class="col-md-9 personal-info">
        <div class="alert alert-info alert-dismissable">
          <a class="panel-close close" data-dismiss="alert">×</a> 
          <i class="fa fa-coffee"></i>
          Do you want to edit your profile...???
        </div>
        <h3>Personal info</h3>
        
        <form class="form-horizontal" role="form">
          <div class="form-group">
            <label class="col-lg-3 control-label">First name:</label>
            <div class="col-lg-8">
            
              <%= f.text_field :firstname ,class: 'form-control'%>    
            </div>
          </div>
          <br>

          <div class="form-group">
            <label class="col-lg-3 control-label">Last name:</label>
            <div class="col-lg-8">
               <%= f.text_field :lastname  ,class: 'form-control'%>
            </div>
          </div>
          <br>
          
          <div class="form-group">
            <label class="col-lg-3 control-label">Date Of Birth:</label>
            <div class="col-lg-8">
              
              <%= f.date_field :dateofbirth ,{class:'form-control datepicker' }%>
            </div>
          </div>
          <br>

          <div class="form-group">
            <label class="col-lg-3 control-label">Gender:</label>
            <div class="col-lg-8">
              <div class="field">
              <%= f.radio_button :gender, 'Female' %> Female
              <%= f.radio_button :gender, 'Male' %> Male
              <%= f.radio_button :gender, 'Other' %> Other
  </div>
            </div>
          </div>
          <br>

          <div class="form-group">
            <label class="col-lg-3 control-label">Country:</label>
            <div class="col-lg-8">
              <%= f.country_select :country, ["India"],{},{class:"form-control"}%>
            </div>
          </div>
          <br>
          <div class="form-group">
            <label class="col-lg-3 control-label">User Type</label>
            <div class="col-lg-8">
              <%= f.select(:usertype, ["Student","Teacher","Other"], {}, {class: "form-control"}) %>
                 
            </div>
          </div>
          <br><br>

          <div class="form-group">
            <label class="col-lg-3 control-label">Qualification:</label>
            <div class="col-lg-8">
               <%=f.text_field :qualification ,class: 'form-control'%>
            </div>
          </div>
          <br>

          <div class="form-group">
            <label class="col-md-3 control-label">Interests:</label>
            <div class="col-md-8">
              <div class="field">
                   <% @subjects.each do |subject| %>
                <%= check_box_tag "userdetail[interests][]", subject.subjectname,checked(subject.subjectname) , id: subject.id,  :style => "float:left;"  %>
              <%= label subject.id, subject.subjectname, {class: "checkbox inline"} %>
              <% end %>
                </div>
            </div>
          </div>
          <br>

          <div class="form-group">
            <label class="col-md-3 control-label"></label>
            <div class="col-md-8">
              <%= f.submit class:'btn btn-primary'%>
              <span></span>
              <input class="btn btn-default" value="Cancel" type="reset">
            </div>
          </div>

        </form>
      </div>
  </div>
</div>
<hr>
<% end %>
<script>
      function readURL(input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
            $('#img_prev')
              .attr('src', e.target.result)
              .width(150)
              .height(200);
          };

          reader.readAsDataURL(input.files[0]);
        }
      }
</script> 
</body>

app/views/userdetails/edit.html.erb
<%= render "layouts/header" %>


<%= render 'form', userdetail: @userdetail %>

app/views/userdetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Userdetails</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Dateofbirth</th>
      <th>Gender</th>
      <th>Country</th>
      <th>Interests</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userdetails.each do |userdetail| %>
      <tr>
        <td><%= userdetail.firstname %></td>
        <td><%= userdetail.lastname %></td>
        <td><%= userdetail.dateofbirth %></td>
        <td><%= userdetail.gender %></td>
        <td><%= userdetail.country %></td>
        <td><%= userdetail.interests %></td>
        <td><%= link_to 'Show', userdetail %></td>
        <td><%= link_to 'Edit', edit_userdetail_path(userdetail) %></td>
        <td><%= link_to 'Destroy', userdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userdetail', new_userdetail_path %>

app/views/userdetails/new.html.erb
<h1>New Userdetails</h1>

<%= render 'form', userdetail: @userdetail %>

app/views/userdetails/show.html.erb
<!--new code starts -->
<%= render "layouts/header" %>
<style>

.timeline {
    list-style: none;
    padding: 20px 0 20px;
    position: relative;
}
.timeline::before {
    top: 0;
    bottom: 0;
    position: absolute;
    content: " ";
    width: 3px;
    background-color: #eeeeee;
    right: 25px;
    margin-left: -1.5px;
}
</style>

<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <%= image_tag @userdetail.image , style: 'height:200px;width:200px',class:'center-block img-responsive' %>
        <h2>  <%= @userdetail.firstname.capitalize %> 
        <%= @userdetail.lastname.capitalize %><h2>     
         <p><span class="label label-default" data-toggle="tooltip" title="" data-original-title="1-Month Subscriber"><i class="fa fa-diamond"></i></span> <span class="label label-primary"><%= @userdetail.usertype %></span></p>

      <hr>

      <p class="user-profile-joined">
        <i class="fa fa-clock-o"></i>
        Joined <time datetime="2014-04-16T21:29:39Z" data-local="time-ago" title="April 17, 2014 at 2:59am IST">on <%= @userdetail.created_at %></time>
      </p>
      
      <p><i class="fa fa-diamond"></i> <%= @questions.where(:user_id=>@userdetail.user_id).count %> questions answered</p>

      <hr>
      <% if current_user.id==@userdetail.user_id %>
      <%= link_to 'Edit' ,edit_userdetail_path(current_user), class: 'btn btn-default btn-lg'%>
      <% end %>

    </div>


   
  <div class="col-sm-9">   
      <hr>
      <ul id="tabs" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#tab" aria-controls="tab" role="tab" data-toggle="tab">Personal Details</a></li>
        <li role="presentation"><a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab">Projects</a></li>
       
      </ul>
      <div class="tab-content">
        
        <div role="tabpanel" class="tab-pane active" id="tab"><br>
                  <h2> <%= @userdetail.firstname.capitalize %> 
                  <%= @userdetail.lastname.capitalize %><h2>
                  <p><strong>Date of Birth: </strong>  <%= @userdetail.dateofbirth %></p>
                  <p><strong>Gender: </strong>  <%= @userdetail.gender %></p>
                  <p><strong>Country: </strong>  <%= @userdetail.country %>DIA</p>
                  <p><strong>I am a : </strong>  <%= @userdetail.usertype %></p>
                <p><strong>Qualification: </strong>  <%= @userdetail.qualification %></p>

                <p><strong>Skills: </strong>                              
                <%= @userdetail.interests %>
                             
                </p>
              
          </div>



        <div role="tabpanel" class="tab-pane" id="tab3">
           
         
            
            <!-- project start -->
            <div class="container">
              <div class="page-header">
                <h1 id="timeline">Projects</h1>
              </div>
              <ul class="timeline" >
                <% @projects.each do |project| %>
                <li >
                  <div class="timeline-badge"><i class="glyphicon glyphicon-check"></i></div>
                  <div class="timeline-panel" style="background-color: white">
                    <div class="timeline-heading">
                      <h4 class="timeline-title"><%=project.title %></h4>
                      <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i><%= project.created_at%></small></p>
                    </div>
                    <div class="timeline-body">
                      

                      <p><i class="fa fa-file"></i>&emsp;<%= project.description%></p><br>
                      
                      <button type="button" class="btn btn-primary btn-sm" >
                          <i class="fa fa-link"></i> LINK<%= link_to '', project.githublink %> 
                        </button>
                     
                        
                        <% if project.user_id == current_user.id %>
                           

                                  <%= link_to '<i class="glyphicon glyphicon-pencil">&nbsp;</i>'.html_safe, edit_project_path(project),class:"btn btn-primary btn-sm" %> 
                                
                               <%= link_to '<i class="glyphicon glyphicon-trash">&nbsp;</i>'.html_safe, project, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary btn-sm"%>
                            </button>
                            
                        <% end %> 
                    </div>
                  </div>
                </li>
                <% end %>
                
                <!-- add project -->

                 <% if current_user.id==@userdetail.user_id %>
                       
                    <%= render  "projects/form" ,project: @project %>
                 
                  <% end %>
                <!-- end add project -->
              </ul>
            <!-- project end -->
            <br>
            
        </div>
       
        </div>
      </div>
    </div>
  
  </div>
</div>
<%= render 'layouts/footer' %>















 