config/routes.rb
Rails.application.routes.draw do
 
  resources :projects
  get 'dislikes/index'

  get 'dislikes/destroy'

  get 'likes/index'

  get 'likes/destroy'

  get 'likes/destroy', to: "likes#destroy"

  get 'myquestions/index'

  get 'questions/answeredque'  

  get 'questions/myquestionsindex'
  
  get 'questions/interestwisequestions'

  get 'questions/changetext'

  get 'questions/searchtext'


  get 'home/aboutus'

root  "home#index"
 




  resources :questions do
  		resources :answers
  	end
  	
  resources :userdetails
  devise_for :users, controllers: { registrations: "registrations" }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :user 
	belongs_to :question 
	has_many :likes, dependent: :destroy
	has_many :dislikes, dependent: :destroy

	validates :useranswer, :presence => true
	validates :useranswer, :length => {:minimum => 10}
	validates :useranswer, :uniqueness =>true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dislike.rb
class Dislike < ApplicationRecord
	belongs_to :user
	belongs_to :answer  
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :answer  
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	validates :title,:technology, :presence => true
	validates :title,:technology, :length => {:minimum => 4}
end

app/models/question.rb
class Question < ApplicationRecord

	belongs_to :user
	has_many :answers, dependent: :destroy
	belongs_to :subject
	validates :userquestion, :presence => true
	validates :userquestion, :length => {:minimum => 9}
	validates :userquestion, :uniqueness =>true
end

app/models/subject.rb
class Subject < ApplicationRecord

	#belongs_to :user
	has_many :questions, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

	 has_many :subjects, dependent: :destroy
	 has_many :questions, dependent: :destroy
	 has_many :answers, dependent: :destroy
   has_many :projects, dependent: :destroy
   has_one :userdetail, dependent: :destroy
   has_one :like, dependent: :destroy
   has_one :dislike, dependent: :destroy
end

app/models/userdetail.rb
class Userdetail < ApplicationRecord
	
	has_attached_file :image, styles: { medium: "50x50#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	belongs_to :user

end

app/helpers/answeredque_helper.rb
module AnsweredqueHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/myquestions_helper.rb
module MyquestionsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/userdetails_helper.rb
module UserdetailsHelper

	def checked(area)
		@userdetail.interests.nil? ? false : @userdetail.interests.match(area)
	end
end

app/views/layouts/_footer.html.erb
<style>
footer {
    background-color: #1B1F21;
    color: #ccc;
    border-top: 4px solid #e7e7e7;
    margin-top: 100px;
    padding: 30px 0px;
}
footer a {
    color: #ccc;
}
.footerleft { margin-top:5px;  }
.logofooter { margin-bottom:10px;margin-left: 30px; font-size:25px; color:white; font-weight:700;}
.logofooter1 { margin-bottom:10px; font-size:25px; color:white; font-weight:700;}

</style>
<footer role="contentinfo">
  <div class="container">
   <div class="row">
      <div class="col-sm-2">
        <div><a href="/"><img class="img-responsive" style="max-height:100px" src="/assets/logo-white.png" alt="Logo white"></a></div>
        <br>
        <div><small><a href="http://excid3.com" target="_blank">@created on 15th April,2017</a></small></div>

      </div>  
      <div class="col-md-6 footerleft">
        <div class="logofooter">
          <strong >
            Our team
          </strong>
        </div>
          <p>Swaranjali Rajendra Sawant &nbsp;&nbsp;&nbsp;&nbsp;- 2014BCS026<br>
            Tejaswini Dhondiram Patil &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- 2014BCS030<br>
            Pooja Govardhan Pogul&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- 2015BCS205<br><br>
            Phone No &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- 8485870947<br><br>
            Email id&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- sawant12262@gmail.com
          </p>    
      </div>
      <div class="col-sm-4 ">
        <div class="logofooter1"><strong>Our Interests</strong></div><br>
        <div> Technologies / Academics</div>
        <div> Open Source</div>
        <div>Science </div>
        <div>Clubs and Events</div>
        <div>Life / Arts</div>
        <div>Social Awareness</div>

        <div>Incredible India!</div>
        <div>Women Empowerment in India </div>
        <div>Travel and Photography</div>
        <div> Psychology </div>
        <div>Culture / Recreation </div>
        <div>Food </div>
        
      </div>  
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<style>
.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    padding: 12px 16px;
    z-index: 1;
}

.dropdown:hover .dropdown-content {
    display: block;
}
.navbar-login
{
    width: 305px;
    padding: 10px;
    padding-bottom: 0px;
}

.navbar-login-session
{
    padding: 10px;
    padding-bottom: 0px;
    padding-top: 0px;
}

.icon-size
{
    font-size: 87px;
}

</style>

  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog model-lg">
      
      <div class="modal-content">
     
        <div class="modal-body">
         <div  id="box1"></div>
        </div>
      </div>
      
    </div>
  </div>
  

<div class='navbar navbar-default' role='navigation'>
  <div class="container-fluid" style='margin-left:50px'>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header-left" >
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <img class='img-responsive pull-left' style='max-height:40px;margin:10px' src='/assets/logo-black.png' alt='Logo white'>
      <%= link_to "<font style='text-decoration:none; font-size:25px'><b>IndexOutOfBounds</b></font>".html_safe, root_path, class: "navbar-brand" %>
    
   

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="col-sm-3 col-md-3">
        <form class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" data-toggle="modal" style='width:500px;' data-target="#myModal" name="q" id="box">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
        </form>
    </div>

</div> 
      
      <ul class="nav navbar-nav pull-right" style='margin-right:50px'>
        
        <li><%= link_to "About", home_aboutus_path %></li>

        <% if current_user %>
     


            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <span class="glyphicon glyphicon-user" style='font-size:25px;'></span>
                        <b><%= @userdtl.find(current_user.id).firstname %></b>
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="navbar-login">
                                <div class="row">
                                    <div class="col-lg-4">
                                        <p class="text-center">
                                      <%= image_tag @userdtl.find(current_user.id).image, class:'img-rounded avatar' , style: 'height:80px;width:80px' %> 
                                        </p>
                                    </div>
                                    <div class="col-lg-8">
                                        <p class="text-left" style='font-size:20px'><strong><%= @userdtl.find(current_user.id).firstname+' '+@userdtl.find(current_user.id).lastname%></strong></p>
                                            
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="divider navbar-login-session-bg"></li>


            <li><%= link_to "<i class='glyphicon glyphicon-user'></i>&emsp;Profile".html_safe, userdetail_path(current_user.id) %></li>
            
            <li class="divider"></li>

                     <li><a href="#"><%= link_to " <i class='fa fa-cog'></i>&emsp;Account Settings".html_safe, edit_user_registration_path %></a></li>


            <li class="divider"></li>

            <li><%= link_to "<i class='fa fa-question-circle'></i>&emsp;My Questions".html_safe,  questions_myquestionsindex_path %></li>

            <li class="divider"></li>

            <li><%= link_to '<i class="fa fa-check-circle"></i>&emsp;My Answers'.html_safe,questions_answeredque_path %></li>

            <li class="divider"></li>

            <li><%= link_to "  <i class='fa fa-sign-out'></i>&emsp; Logout".html_safe, destroy_user_session_path, method: :delete %><br></li>
            <li class="divider"></li>
                    </ul>

        <% else %>
            
            <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
     
 

        
      </ul>


  </div><!-- /.container-fluid -->
</div>


<script type="text/javascript">
$('#box').on('input',function(e){
  
    $.ajax({ url: "questions/searchtext?q=" +$('#box').val()})
  
    });

</script>

app/views/layouts/_leftstack.html.erb
<div class="col-md-3 ">
        <div class="panel panel-default">
          <div class="panel-body">
                <% if !(request.original_url.include? '/questions/myquestionsindex') && !(request.original_url.include? '/questions/') %>
                <%= link_to '<h4>Ask a Question</h4>'.html_safe,new_question_path,:class=>'btn btn-default',:style=>"width: 100%;margin-bottom:0;","data-toggle" => "modal",'data-target'=> '#loginModal' %>
                <hr>
                <% end %>
            
              <h4 class="alert alert-info" align="center"><strong>Activities</strong></h4>
         
              <div><i class="fa fa-bars"></i> All Threads </a></div>
              <div><i class="fa fa-check"></i><%= link_to'Answered:',questions_answeredque_path%><span class="badge badge-theme"><%= @cnt %></span></div>
              <br>
                <h4 class="alert alert-info" align="center"><strong> Subjects</strong></h4>
                  <div class="h-divider"></div>
                    <% @subjects.each do |subject| %>
                         <% if @userdtl.find(current_user.id).interests.include? subject.subjectname %>
                          <p class='text-primary' style='font-size:17px;'>•&emsp;<%= link_to subject.subjectname, questions_interestwisequestions_path(:subjectname => subject.subjectname) %> <span class="badge badge-theme pull-right">
                        <%= @questions.where(:subject_id => subject.id).count %>
          </span></p>
                <% end %>
                    <% end %>
                <div class="h-divider"></div>      
                  <h4 class="alert alert-info" align="center"><strong> Recent Questions</strong></h4>
                  
                 
                    <% @newquestions.each do |question| %>
                
                      <div class="forum-thread-card" style="margin: 10px" >
                        <div class="row">
                          <a class="thread-posts-count pull-right" href="#">
                            <span class="badge badge-theme" style="background-color:#158CBA;"><%= question.answers.count%>
                                
                            </span>
                          </a>  
                          <div>
                                <%= image_tag @userdtl.find(question.user_id).image, class: 'img-rounded avatar pull-left', style: 'height:40px;width:40px; margin-right:20px' %>
                           </div>
                           </div>
                            <div class="row">
                                <h5>
                                    <i class="fa fa-thumb-tack fa-text-muted text-muted"></i> 
                                    <%= link_to question.userquestion, question %>
                                  
                                </h5>
                              </div>
                                <div class="thread-details">
                                  <small>
                                  <strong><a style="color: #4ea1d3"><%= question.subject.subjectname.upcase %></a></strong>
                                  • Asked <time datetime="2016-10-26T16:35:23Z" data-local="time-ago"><%= time_ago_in_words(question.created_at)%> ago </time> by <%= link_to @userdtl.find(question.user_id).firstname.upcase, userdetail_path(question.user_id) ,:style=>"color:#158CBA"%> 
                                    </small>
                                </div>
                           
                          <br>
                      </div>
                      <!-- end of forum card -->
                       <div class="h-divider">
                        </div>
                      
                
                      <% end %>
        
                
                    <hr>
            
          </div> 
          <!-- end of panel body -->
        
        </div> 
        <!-- end of panel default -->
  </div>
      <!-- end of col md 3 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IOB</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>